// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Proyecto.Models;

namespace Proyecto.Migrations.Vacuna
{
    [DbContext(typeof(VacunaContext))]
    [Migration("20190714011209_Vacuna")]
    partial class Vacuna
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Proyecto.Models.VacunaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<string>("Fecha");

                    b.Property<string>("Nombre");

                    b.Property<string>("NombreVacuna");

                    b.Property<string>("Telefono");

                    b.HasKey("Id");

                    b.ToTable("VacunaItems");
                });
#pragma warning restore 612, 618
        }
    }
}
