// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Proyecto.Models;

namespace Proyecto.Migrations.Cliente
{
    [DbContext(typeof(ClienteContext))]
    [Migration("20190709143813_ClienteDB")]
    partial class ClienteDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Proyecto.Models.ClienteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<string>("Correo");

                    b.Property<int>("Edad");

                    b.Property<string>("Nombre");

                    b.Property<string>("NombreMascota");

                    b.Property<string>("Raza");

                    b.Property<string>("Telefono");

                    b.HasKey("Id");

                    b.ToTable("ClienteItems");
                });
#pragma warning restore 612, 618
        }
    }
}
